_target_: interpretability.task_modeling.task_env.multi_task_env.MultiTaskWrapper
dataset_name: MultiTaskMemAnti
task_list:
  - DelayPro
  - DelayAnti
  - MemoryPro
  - ReactPro
  - ReactAnti

n_timesteps: 640
noise: 0.3
num_targets: 32
bin_size: 20
grouped_sampler: True
