_target_: interpretability.task_modeling.datamodule.task_datamodule_coupled.TaskDataModuleCoupled
data_env:
  _target_: motornet.environment.RandomTargetReach
  effector:
    _target_: motornet.effector.ReluPointMass24
  max_ep_duration: 1.0
n_samples: 1000
seed: 0
batch_size: 256
num_workers: 4