raster_plot:
  _target_: lfads_torch.callbacks.RasterPlot
  log_every_n_epochs: 100

trajectory_plot:
  _target_: lfads_torch.callbacks.TrajectoryPlot
  log_every_n_epochs: 100

cond_avg_trajectory_plot:
  _target_: lfads_torch.callbacks.CondAvgTrajectoryPlot
  log_every_n_epochs: 100

r2_activations:
  _target_: lfads_torch.extensions.armnet.ActivationR2
  log_every_n_epochs: 100

cond_avg_raster:
  _target_: lfads_torch.extensions.armnet.CondAvgRaster
  log_every_n_epochs: 100
