_target_: interpretability.task_modeling.task_env.task_env.RandomTargetDelay
effector:
  _target_: motornet.effector.RigidTendonArm26
  muscle:
    _target_: motornet.muscle.MujocoHillMuscle
max_ep_duration: 3.0
