_target_: interpretability.data_modeling.lfads_torch.datamodules.BasicDataModule
data_paths:
  - ${relpath:datasets/3BFF_model_TaskTrainedRNN_n_neurons_50_nonlin_embed_False_obs_noise_poisson_seed_0.h5}
batch_keys:
  - inputs
  - latents
  - activity
batch_size: 256
