model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: "."
  monitor: valid/loss_all
  save_last: True

model_checkpoint_2:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: "."
  monitor: valid/loss_all
  filename: "best_{epoch}_loss_{val_loss:.2f}"
  save_last: False

tune_report_callback:
  _target_: ray.tune.integration.pytorch_lightning.TuneReportCallback
  metrics:
    loss: valid/loss_all

neural_speed_callback:
  _target_: dmfc_learning.callbacks.dmfc_callbacks.NeuralSpeedCallback
  log_every_n_epochs: 100

raster_plot_callback:
  _target_: dmfc_learning.callbacks.dmfc_callbacks.RasterPlotCallback
  log_every_n_epochs: 100

psth_callback:
  _target_: dmfc_learning.callbacks.dmfc_callbacks.PSTHCallback
  log_every_n_epochs: 100
  conds_to_use: ["is_short", "ts"]

psth_callback2:
  _target_: dmfc_learning.callbacks.dmfc_callbacks.PSTHCallback
  log_every_n_epochs: 100
  conds_to_use: ["is_eye", "ts"]

psth_callback3:
  _target_: dmfc_learning.callbacks.dmfc_callbacks.PSTHCallback
  log_every_n_epochs: 100
  conds_to_use: ["theta", "ts"]

trajectory_plot_callback:
  _target_: dmfc_learning.callbacks.dmfc_callbacks.TrajectoryPlotCallback
  log_every_n_epochs: 100

inputs_plot:
  _target_: dmfc_learning.callbacks.dmfc_callbacks.InputsPlot
  log_every_n_epochs: 100

traj_plot_cond_avg_callback:
  _target_: dmfc_learning.callbacks.dmfc_callbacks.TrajectoryPlotCondAvgCallback
  log_every_n_epochs: 100

quiver_plot_callback:
  _target_: dmfc_learning.callbacks.dmfc_callbacks.QuiverPlotCallback
  log_every_n_epochs: 400

uvector_callback:
  _target_: dmfc_learning.callbacks.dmfc_callbacks.ComputeUVectorCallback
