_target_: interpretability.task_modeling.task_env.multi_task_env.MultiTaskWrapperGeneralize
dataset_name: MultiTaskMemAnti
task_list:
  - MemoryAnti

n_timesteps: 640
noise: 0.3
num_targets: 32
bin_size: 20
grouped_sampler: True
