_target_: interpretability.task_modeling.task_env.multi_task_env.MultiTaskWrapper

task_list:
  - DelayPro
  - DelayAnti
  - MemoryPro
  - MemoryAnti
  - ReactPro
  - ReactAnti
  - ContextIntMultimodal
  - Match2Sample
  - NonMatch2Sample
  - MatchCatPro
  - MatchCatAnti

n_timesteps: 640
noise: 0.15
num_targets: 32
bin_size: 20
grouped_sampler: False
