_target_: dmfc_learning.datasets.task_trained_data.TaskTrainedRNNDataModule
system: NBitFlipFlop
gen_model: TaskTrainedNODE
n_neurons: 50
obs_noise: poisson
seed: 0
batch_size: 64
num_workers: 4
nonlin_embed: True
provide_inputs: False
epoch: 100
