raster_plot:
  _target_: interpretability.data_modeling.data_training.callbacks.RasterPlot
  log_every_n_epochs: 100

# trajectory_plot:
#   _target_: interpretability.data_modeling.data_training.callbacks.TrajectoryPlot
#   log_every_n_epochs: 100
