raster_plot:
  _target_: interpretability.data_modeling.data_training.callbacks.RasterPlot
  log_every_n_epochs: 100

trajectory_plot:
  _target_: interpretability.data_modeling.data_training.callbacks.TrajectoryPlot
  log_every_n_epochs: 100

input_accuracy:
  _target_: interpretability.data_modeling.data_training.extensions.task_trained.InputR2Plot
  log_every_n_epochs: 20
  n_samples: 16
